import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] });

export default function Home() {

  function handleChange(event: { target: { value: any; }; }) {

    const seed = event.target.value;
    const codeLength = seed.length;

    if(codeLength == 12) {
      checkSeed(seed);
    }
  }

  async function checkSeed(seed: Object) {

    const body = {
      seed,
    }

    const res = await fetch('/api/seed', {
        method: 'POST',
        body: JSON.stringify(body),
    });

    const seedObj = await res.json();
    console.log(seedObj);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        welcome to the sagittarii club
      </div>
      <div>
        <input size={25} placeholder="Enter your seed here" type="text" id="first" name="first" onChange={handleChange} />
      </div>
    </>
  )
}
