import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] });

export default function Home() {

  function handleChange(event: { target: { value: any; }; }) {

    const accessCode = event.target.value;
    const codeLength = accessCode.length;

    if(codeLength == 16) {
      checkCode(accessCode);
    }
  }

  async function checkCode(code: String) {
    // console.log(code);
    const res = await fetch('/api/entries', {
        method: 'POST',
    });
    const data = await res.json();
    console.log(data);
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        welcome to the sagittarii club
      </div>
      <div>
        <input size={25} placeholder="Enter your access code here" type="text" id="first" name="first" onChange={handleChange} />
      </div>
    </>
  )
}
