// import Image from 'next/image';
// import styles from '@/styles/Home.module.css';
// import { Inter } from 'next/font/google';
// const inter = Inter({ subsets: ['latin'] });
import Head from 'next/head';
import Router from 'next/router';
import React, { useState } from 'react';

export default function Home() {
  const [message, setMessage] = useState('');

  function handleChange(event: { target: { value: any; }; }) {
    setMessage('needs to have 12 digits');

    const seed = event.target.value;
    const codeLength = seed.length;

    if(codeLength == 12) {
      setMessage('please wait..');
      checkSeed(seed);
    };

  }

  async function checkSeed(seed: any) {

    const body = {
      seed,
    }

    const res = await fetch('/api/seed', {
        method: 'POST',
        body: JSON.stringify(body),
    });

    const seedObj = await res.json();

    if(seedObj.status == 'ok') {
      setMessage('please wait..');
      Router.push({
        pathname: '[seed]',
        query: { seed },
      })
    } else {
      setMessage('seed does not exist');
    }

  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        welcome to the sagittarii club
      </div>
      <div>
        <input size={25} placeholder="Enter your seed here" type="text" id="first" name="first" onChange={handleChange} />
        <div>
          { message }
        </div>
      </div>
    </>
  )
}
